### ISSUE TITLE
New enhanced Frontend Design (Using pure HTML CSS JS)

### ISSUE THREAD

**Issue by Zack-Dx** [Zack-Dx/Jsonify-RestAPI#10]
Design the updated frontend for the API so that it's more unique and descriptive  and make sure it's responsive too.

**Comment by Panth1823** [comment]
Hey i would like to work on this issue @Zack-Dx

**Comment by Zack-Dx** [comment]
@Panth1823 sure just whatever u do make a new folder named panth-frontend and then commit it.
